### ISSUE TITLE
IsPointer/instances.pointer not implemented

### ISSUE THREAD

**Issue by NotNite** [pohky/XivReClassPlugin#9]
Repro case: `<Client::Game::Event::EventFramework_Instance>`. Will point to the location in the executable instead of the contents in memory. This is because of how it's defined in CS:

```yml
Client::Game::Event::EventFramework:
  instances:
    - ea: 0x14216CEB8
      pointer: True
```

This can be worked around by making two classes and assigning the "real" class as a pointer child of the "fake" class:

![image](https://github.com/pohky/XivReClassPlugin/assets/44414597/911bd91c-80cd-4a6a-850f-d0fb3f799e87)
